# Site settings
title: 社会你鑫哥的博客
SEOTitle: 社会你鑫哥的博客 | MY Blog
header-img: img/post-bg-desk.jpg
email: 1152381447@qq.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 社会你鑫哥的博客, dixin, 鑫哥, iOS, Apple, iPhone"
url: "https://blog.csdn.net/qq_36771269"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dixin0429/dixin0429.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/my.jpg       # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     yong-yuan-shi-ba-sui-30
github_username:    dixin0429
#facebook_username:  baiying.qiu.7
jianshu_username:   19559450
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 55ea6dbbe34c6b8cd8ac                            #生成的clientID
  clientSecret: 0c928fd6c63da0eeca8bff4aeb2e50a5347f3268    #生成的clientSecret
  repo: dixin0429.github.io    #仓库名称
  owner: dixin0429    #github用户名
  admin: dixin0429
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
